name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: cypress-io/cypress@1
    - run: npx cypress run --executor cypress/browsers-chrome73-ff68 --record --key 07654803-b572-49bd-9625-2be6eacdae25 --parallel --parallelisim 4 --group Chrome --browser chrome
    - run: npx cypress run --executor cypress/browsers-chrome73-ff68 --record --key 07654803-b572-49bd-9625-2be6eacdae25 --parallel --parallelisim 4 --group Firefox --browser firefox
