name: Node.js with Cypress Dashboard and parallelism
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npx percy exec cypress --executor cypress/browsers-chrome73-ff68  --parallel --record --key 07654803-b572-49bd-9625-2be6eacdae25 --parallelism 4 --group Chrome --browser chrome
    #  run: npx cypress run --executor cypress/browsers-chrome73-ff68 --record --key 07654803-b572-49bd-9625-2be6eacdae25 --parallel --parallelism 4 --group Firefox --browser firefox
      env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
